
# GET http://localhost:3000

### user - create
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "asdd1234@sdf.com",
    "passwd": "12345"
}

### user - login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "asdd123@sdf.com",
    "passwd": "12345"
}

### user  - email check
GET http://localhost:3000/users/signup/check?email=asdd123@sdf.com